### ISSUE TITLE
More ways of setting fire to gasoline

### ISSUE THREAD

**Issue by Giorgi3333** [Hypatech/ULTRAKILL-Speedrunner-Issues#15]
currently, you can set fire to gasoline using a pro boost, a core, a rocket and a parried projectile. this is both unintuitive and limiting, having other explosions set fire to the gasoline would open up more opportunities for interactions and synergy mid combat, while also being logically consistent. explosions such as an overpump, fireworks, fups, core snipes, srs snipes, malrail shots and nukes should also light the gasoline on fire imo.

**Comment by Hypatech** [comment]
Lots added in the last hotfix!
