### ISSUE TITLE
A speedometer that can be activated using the console

### ISSUE THREAD

**Issue by 10-days-till-xmas** [Hypatech/ULTRAKILL-Speedrunner-Issues#20]
This would be just as useful as the ssjIndicator. The options should be horizontal speed+ vertical speed, all 3 directions, and a magnitude-direction form (just magnitude would be useful though)

**Comment by Hypatech** [comment]
Workin on it 

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/27899907/f241e3ef-e777-4709-b235-6d4e90b50b53
