### ISSUE TITLE
Underwater oil explosions spawn too many explosions, causing lag and balance issues

### ISSUE THREAD

**Issue by 10-days-till-xmas** [Hypatech/ULTRAKILL-Speedrunner-Issues#21]
https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/159474213/a163d8ba-d6c8-48cc-b032-f94913e5ab0b
One idea that could work is making it so that voxels within range of an oil explosion won't detonate, but will cause voxels next to it to explode, preventing having excessive explosions. And since this'll be inconsistent for damage, maybe all explosions from oil can only hit an enemy once, further preventing issues with doing excessive damage

**Comment by Hypatech** [comment]
Should be reduced in next patch. Leave another comment here if its still too much and ill re-open
