### ISSUE TITLE
Please keep the alt shotgun bug where you can do shit during hitstop

### ISSUE THREAD

**Issue by Giorgi3333** [Hypatech/ULTRAKILL-Speedrunner-Issues#23]
So theres a "bug" (i think??) where you can do smth extra during the alt shotguns slowdown, like pump ur shotgun an extra time, or release shoot the chainsaw. I think this is sick and opens up new possibilites for stuff and it should stay. 

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/2636b60d-81c1-4e35-87f9-3842e0b9525f

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/9379804e-dcb4-4698-85be-891aa827d4b2

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/6e3abe4c-41ad-4e48-b3a8-fca56e94a1ad

**Comment by Hypatech** [comment]
Very very cool, if I catch someone trying to 'fix' it ill let them know, but if it slips past me please bother me on this issue and ill re-open it

**Comment by Giorgi3333** [comment]
goat stays goating
