### ISSUE TITLE
Adding the Cybergrind wave number to StatsManager

### ISSUE THREAD

**Issue by 10-days-till-xmas** [Hypatech/ULTRAKILL-Speedrunner-Issues#3]
This'll allow for livesplit to be able to use wave number to split, so that LS can be useful in cybergrind runs as well

**Comment by Hypatech** [comment]
Could potentially do this if just using EndlessGrid.currentWave isnt feasible.

**Comment by 10-days-till-xmas** [comment]
Your suggestion worked thanks!! There seems to be minor inconsistencies but that's to be expected (livesplit updates the time AFTER splitting), and I have ideas on how to correct it
