### ISSUE TITLE
Gasoline explosions underwater are broken (also remove the water in p-2 stalker room)

### ISSUE THREAD

**Issue by Giorgi3333** [Hypatech/ULTRAKILL-Speedrunner-Issues#31]
rn each a line of oil produces a bunch of small explosions which deals a fuck ton of damage, i say either reduce the damage of each explosion or make it one big explosion

(also is there a way to not make the gasoline explode on the solid surface in the middle of stalker room in p-2)

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/a8e5884e-42c3-4048-99da-cd848e5b4fd4

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/85641248-8524-415f-a84e-244158cdacad

https://github.com/Hypatech/ULTRAKILL-Speedrunner-Issues/assets/167441401/905cbc96-911c-41e4-a0ec-98b4e69a7bf9

**Comment by Hypatech** [comment]
Excessive explosiosn will be fixed in the next patch. Feel free to make a seperate issue for the stalker p-2 room if its still a problem
